name: Build

on:
  push:
    branches: [ "master" ]
    paths:
    - .github/workflows/build.yml
    - AudioLink/**
    - AudioLink.sln

jobs:
  build:
    name: Build
    strategy:
      matrix:
        game-version: [ 1.29.1, 1.34.2, 1.37.1 ]
    uses: Aeroluna/workflows/.github/workflows/bs-build-version-release.yml@main
    with:
      project-path: AudioLink/AudioLink.csproj
      game-version: ${{ matrix.game-version }}
    secrets: inherit

  create_release:
    name: Create Release
    needs: build
    permissions:
      contents: write
    uses: Aeroluna/workflows/.github/workflows/bs-create-release-from-project.yml@main
    with:
      project-path: AudioLink/AudioLink.csproj
    secrets: inherit

  upload:
    name: Upload
    needs: build
    uses: Aeroluna/workflows/.github/workflows/bs-upload-to-beatmods.yml@main
    with:
      mods: '{"AudioLink": 261}'
    secrets:
      token: ${{ secrets.PAT }}
